#!/bin/sh
set -e
INSTALL_ROOT="/usr/share/webrtchub"
cd "$INSTALL_ROOT"

# Create venv only if not present
if [ ! -d .venv ]; then
  python3 -m venv .venv
  . .venv/bin/activate
  pip install --upgrade pip
  pip install -r requirements.txt
fi
exit 0
